// <auto-generated />
using AuthorInfo.API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthorInfo.API.Migrations
{
    [DbContext(typeof(AuthorInfoContext))]
    [Migration("20210207221535_DummyData")]
    partial class DummyData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuthorInfo.API.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ShortBio")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new { Id = 1, Name = "Ian Rankin", ShortBio = "Ian James Rankin (born 28 April 1960) is a Scottish crime writer, best known for his Inspector Rebus novels." },
                        new { Id = 2, Name = "Philip Kerr", ShortBio = "Philip Ballantyne Kerr (22 February 1956 – 23 March 2018) was a British author, best known for his Bernie Gunther series of historical detective thrillers." },
                        new { Id = 3, Name = "Adrian McKinty", ShortBio = "Adrian McKinty is a Northern Irish writer of crime and mystery novels and young adult fiction, best known for his Sean Duffy novels set in Northern Ireland during The Troubles." }
                    );
                });

            modelBuilder.Entity("AuthorInfo.API.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(300);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new { Id = 1, AuthorId = 1, Synopsis = "Knots and Crosses is a 1987 crime novel by Ian Rankin. It is the first of the Inspector Rebus novels. It was written while Rankin was a postgraduate student at the University of Edinburgh.", Title = "Knots and Crosses" },
                        new { Id = 2, AuthorId = 1, Synopsis = "Hide and Seek is a 1991 crime novel by Ian Rankin. It is the second of the Inspector Rebus novels.", Title = "Hide and Seek" },
                        new { Id = 3, AuthorId = 2, Synopsis = "March Violets is a historical detective novel and the first written by Philip Kerr featuring detective Bernhard \"Bernie\" Gunther. March Violets is the first of the trilogy by Kerr called Berlin Noir.", Title = "March Violets" },
                        new { Id = 4, AuthorId = 2, Synopsis = "The Pale Criminal is a historical detective novel and the second in the Berlin Noir trilogy of Bernhard Gunther novels written by Philip Kerr.", Title = "The Pale Criminal" },
                        new { Id = 5, AuthorId = 3, Synopsis = "Dead I Well May be is a 2003 novel by Irish/Australian author Adrian McKinty. It is his second novel, following Orange Rhymes With Everything, and was nominated for the CWA Ian Fleming Steel Dagger award for the best thriller of the year.", Title = "Dead I Well May Be" },
                        new { Id = 6, AuthorId = 3, Synopsis = "In the Morning I'll be Gone is a 2014 novel by Belfast born novelist Adrian McKinty which won the 2014 Ned Kelly Award for Best Novel. It is the third in the author's Sean Duffy series, following The Cold Cold Ground and I Hear the Sirens in the Street.", Title = "In the Morning I'll Be Gone" }
                    );
                });

            modelBuilder.Entity("AuthorInfo.API.Entities.Book", b =>
                {
                    b.HasOne("AuthorInfo.API.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
